wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.23.0
    framework: huggingface
    huggingface_version: 4.57.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764505632
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      2:
      - 1
      - 11
      - 41
      - 49
      3:
      - 4
      - 13
      - 42
      4: 3.10.18
      5: 0.23.0
      6: 4.57.1
      13: linux-x86_64
    e:
      yrxm7uemyf1po1f3blfzdn48daqc4lsa:
        os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
        python: CPython 3.10.18
        started_at: '2025-11-30T12:27:12.309980Z'
        args:
        - --project
        - 504_neg1
        - --name
        - CocoAndVG
        - --model-name=openai-clip:ViT-B/32
        - --train_path
        - ./data/train_coco_aug_withneg_adjchange_merge.json
        - --test_path
        - ./data/visual_genome_attribution_aug.json
        - --manualSeed
        - '120'
        - --batch_size
        - '32'
        - --lr
        - 5e-6
        - --epoch
        - '10'
        - --weight_decay
        - '0.1'
        - --knowledge_weight
        - '0.2'
        - --transformer_layer_num
        - '6'
        - --neg_loss_weight
        - '5'
        - --device=cuda
        program: /mnt/sdb/wyn/Structure-CLIP-main/./model/train.py
        code_path: model/train.py
        code_path_local: model/train.py
        git:
          remote_url: https://github.com/sdbhcx/structure-clip.git
          commit: 8c806bb61e803fedd87a90c157e44b292ff380ea
        root: /mnt/sdb/wyn/Structure-CLIP-main
        host: junbo-Super-Server
        executable: /home/wyn/.conda/envs/clip-env/bin/python
        cpu_count: 72
        cpu_count_logical: 144
        gpu_type: NVIDIA GeForce RTX 4090
        gpu_count: 4
        disk:
          /:
            total: '1005867986944'
            used: '946609688576'
        memory:
          total: '270003695616'
        gpu_nvidia:
        - name: NVIDIA GeForce RTX 4090
          memory_total: '25757220864'
          cuda_cores: 16384
          architecture: Ada
          uuid: GPU-afdc04c3-88b6-39fe-6ed0-098a0ff297c7
        - name: NVIDIA GeForce RTX 4090
          memory_total: '25757220864'
          cuda_cores: 16384
          architecture: Ada
          uuid: GPU-28151808-1d84-52c8-a1ab-33105e55dc98
        - name: NVIDIA GeForce RTX 4090
          memory_total: '25757220864'
          cuda_cores: 16384
          architecture: Ada
          uuid: GPU-8014a6ba-a920-d8fc-f255-1aa280c3df9a
        - name: NVIDIA GeForce RTX 4090
          memory_total: '25757220864'
          cuda_cores: 16384
          architecture: Ada
          uuid: GPU-538dc88a-6908-d392-5f90-a6083987ec91
        cuda_version: '13.0'
        writer_id: yrxm7uemyf1po1f3blfzdn48daqc4lsa
